src/Entity/Document.php
<?php

namespace App\Entity;

use App\Repository\DocumentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=DocumentRepository::class)
 * @ORM\Table(name="document", uniqueConstraints={
 *       @ORM\UniqueConstraint(name="document_uk", columns={"title","start_date","version","classification_id"})
 * })
 * @ORM\HasLifecycleCallbacks()
 */

class Document
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $text;

    /**
     * @ORM\Column(type="string", length=255)
     */
    #[Assert\NotBlank]
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    #[Assert\NotBlank]
    private $start_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $end_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $state;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $version;

    /**
     * @ORM\ManyToMany(targetEntity=Metadata::class, inversedBy="documents")
     */
    private $metadatas;

    /**
     * @ORM\OneToMany(targetEntity=DocumentRelation::class, mappedBy="document_source")
     */
    private $documentSources;

    /**
     * @ORM\OneToMany(targetEntity=DocumentRelation::class, mappedBy="document_target")
     */
    private $documentTargets;

    /**
     * @ORM\ManyToOne(targetEntity=Classification::class, inversedBy="documents")
     * @ORM\JoinColumn(nullable=false)
     */
    #[Assert\NotBlank]
    private $classification;

    public function __construct()
    {
        $this->metadatas = new ArrayCollection();
        $this->documentSources = new ArrayCollection();
        $this->documentTargets = new ArrayCollection();
        $this->start_date = new \DateTime();
    }

    public function __toString(): string
    {
        return $this->classification.'.'.$this->title.'.'.$this->start_date->format('Y-m-d').'.'.$this->version;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->version;
    }

    public function setVersion(?string $version): self
    {
        $this->version = $version;

        return $this;
    }

    /**
     * @return Collection|Metadata[]
     */
    public function getMetadatas(): Collection
    {
        return $this->metadatas;
    }

    public function addMetadata(Metadata $metadata): self
    {
        if (!$this->metadatas->contains($metadata)) {
            $this->metadatas[] = $metadata;
        }

        return $this;
    }

    public function removeMetadata(Metadata $metadata): self
    {
        $this->metadatas->removeElement($metadata);

        return $this;
    }

    /**
     * @return Collection|DocumentRelation[]
     */
    public function getDocumentSources(): Collection
    {
        return $this->documentSources;
    }

    public function addDocumentSource(DocumentRelation $documentSource): self
    {
        if (!$this->documentSources->contains($documentSource)) {
            $this->documentSources[] = $documentSource;
            $documentSource->setDocumentSource($this);
        }

        return $this;
    }

    public function removeDocumentSource(DocumentRelation $documentSource): self
    {
        if ($this->documentSources->removeElement($documentSource)) {
            // set the owning side to null (unless already changed)
            if ($documentSource->getDocumentSource() === $this) {
                $documentSource->setDocumentSource(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|DocumentRelation[]
     */
    public function getDocumentTargets(): Collection
    {
        return $this->documentTargets;
    }

    public function addDocumentTarget(DocumentRelation $documentTarget): self
    {
        if (!$this->documentTargets->contains($documentTarget)) {
            $this->documentTargets[] = $documentTarget;
            $documentTarget->setDocumentTarget($this);
        }

        return $this;
    }

    public function removeDocumentTarget(DocumentRelation $documentTarget): self
    {
        if ($this->documentTargets->removeElement($documentTarget)) {
            // set the owning side to null (unless already changed)
            if ($documentTarget->getDocumentTarget() === $this) {
                $documentTarget->setDocumentTarget(null);
            }
        }

        return $this;
    }

    public function getClassification(): ?Classification
    {
        return $this->classification;
    }

    public function setClassification(?Classification $classification): self
    {
        $this->classification = $classification;

        return $this;
    }

    /**
    * @ORM\PrePersist
    */
    public function setStartDateValue()
    {
        $this->start_date = new \DateTime();
    }
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\Document;
use App\Repository\DocumentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/document")
 */
class DocumentController extends AbstractController
{
    /**
     * @Route("/{id}", name="document_show", methods={"GET"})
     */
    public function show(Document $document): Response
    {
        return $this->render('document/show.html.twig', [
            'document' => $document,
            'code' => $document->getClassification()->getCode(),
        ]);        
    }
}

templates/document/post_show.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'document_post_show' %}

{% block body %}
    <div class="row">
        <div class="col-12 col-lg-8">
            {% if documents|length > 0 %}
                {% for document in documents %}
                    <div class="media shadow border rounded-lg p-3 mb-4">

                        <div class="media-body">
                            <h4 class="font-weight-light mb-0">
                                <a href="{{ path('document_show', { id: document.id}) }}">
                                {{ document.title }}
                                </a>
                            </h4>
                            <div class="document-text">
                                {{ document.text | raw }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div>There are {{ documents|length }} documents.</div>
            {% else %}
                <div class="text-center">
                    No documents have been posted yet.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/document/search.html.twig
{% extends 'base.html.twig' %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('search') }}
{% endblock %}

{% block body_id 'document_search' %}

{% block body %}
    <form action="{{ path('document_search') }}" method="get">
        <div class="form-group">
            <input name="q"
                   class="form-control search-field"
                   placeholder="{{ 'search.for'|trans }}"
                   autocomplete="off"
                   value="{{ query }}"
                   autofocus
                   data-no-results-message="{{ 'document.no_documents_found'|trans }}"
            >
        </div>
    </form>

    <div id="results">
    </div>
{% endblock %}

templates/document/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Document{% endblock %}

{% block body %}
<tbody>
    <div class="media shadow border rounded-lg p-3 mb-4">
    <table class="table">
            <tr>
                <td colspan=2><h2>
                {{ document.title }}
                </h2></td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ document.id }}</td>
            </tr>
            <tr>
                <th>{{ 'label.text'|trans }}</th>
                <td>{{ document.text  | raw }}</td>
            </tr>
            <tr>
                <th>{{ 'label.start_date'|trans }}</th>
                <td>{{ document.startDate ? document.startDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>{{ 'label.end_date'|trans }}</th>
                <td>{{ document.endDate ? document.endDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>{{ 'label.state'|trans }}</th>
                <td>{{ document.state }}</td>
            </tr>
            <tr>
                <th>{{ 'label.version'|trans }}</th>
                <td>{{ document.version }}</td>
            </tr>
            {% if document.metadatas|length > 0 %}
            <tr>
                <td colspan=2><h2>{{ 'label.tags'|trans }}</h2></td>
            </tr>
            {% endif %}
            {% for metadata in document.metadatas %}
            <tr>
                <th>{{ metadata.getDublinCoreElement }}</th>
                <td><a href="{{ path('document_search', { q: metadata.term}) }}">
                {{ metadata.term }}
                </a></td>
            </tr>
            {% endfor %}
            {% if document.documentSources|length > 0 %}
            <tr>
                <td colspan=2><h2>{{ 'label.sources'|trans }}</h2></td>
            </tr>
            {% endif %}
            {% for relation in document.documentSources %}
            <tr>
                <th>{{ relation.getDublinCoreRelation }}</th>
                <td><a href="{{ path('document_show', { id: relation.getDocumentTarget.getId}) }}">
                {{ relation.getDocumentTarget }}
                </a></td>
           </tr>
            {% endfor %}
            {% if document.documentTargets|length > 0 %}
            <tr>
                <td colspan=2><h2>{{ 'label.targets'|trans }}</h2></td>
            </tr>
            {% endif %}
            {% for relation in document.documentTargets %}
            <tr>
                <th>{{ relation.getDublinCoreRelation }}</th>
                <td><a href="{{ path('document_show', { id: relation.getDocumentSource.getId}) }}">
                {{ relation.getDocumentSource }}
                </a></td>
            </tr>
            {% endfor %}
    </table>
    </div>
    <div>
        <a href="{{ path('classification', {'code': code}) }}">{{ 'classification.redirection'|trans }}</a>
    </div>
</tbody>
{% endblock %}